name: BRUH

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Test SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            mkdir /var/www/thatcoldtoast
            cd /var/www/thatcoldtoast
            git clone https://github.com/Name-Not-Included-Studios/bird-api.git
            cd ./bird-api
            yarn
            yarn dev
